version: "3"
services:
  app:
    build:
      context: .  
    container_name: alias_app
    ports:
      - "3000:3000" 
    env_file:
      - .env 
    depends_on:
      - mongo  
    volumes:
      - ./:/usr/src/app  
    command: npm run watch  

  mongo:
    image: mongo:latest  
    container_name: alias_mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:  
