version: "3"
services:
  app:
    build:
      context: .  # Use the current directory as the build context
    container_name: alias_app
    ports:
      - "3000:3000"  # Expose port 3000 for the app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # Set MongoDB URI
    depends_on:
      - mongo  # Wait for MongoDB to be ready before starting the app
    volumes:
      - ./:/usr/src/app  # Bind mount local directory to /usr/src/app in the container
    command: npm run watch  # Use nodemon for hot-reloading (change this if you don't use nodemon)

  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    container_name: alias_mongo
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:  # Define a named volume for MongoDB data
